### ISSUE TITLE
[Compatibility] Stackable shulker boxes from carpet are set to 1 when adding items

### ISSUE THREAD

**Issue by Decrepitdoors** [kyrptonaught/quickshulker#36]
I have both quick shulker and carpet installed on my server and quick shulker on client. 
When right clicking to add items, stacks of shulker boxes are deleted rather than being moved/dropped or not doing anything. may not be worth working out compatibility but it would make my life easier on my server, I keep having to give my players shulker boxes when they right click the wrong slot in their inventory, also slightly linked to https://github.com/kyrptonaught/quickshulker/issues/17 which I haven't experienced.

**Comment by kyrptonaught** [comment]
This is a tricky one to fix, shulker aren't supposed to be stack-able and this causes massive duplication when using a stacked shulker quickly as the inserted items are copied to all shulkers in the stack. Quickshulker shrinks the stack if it detects them stacked to prevent this dupe. 

Are you using 1.2.3? This release prevented you from even interacting with stacked shulkers. This should fix the disappearing issue, but prevent them from being opened

**Comment by MeeniMc** [comment]
I have tried in singleplayer only so far, but in 1.2.5 this appears to be only partially resolved
1. the original bug is removed by preventing all interactions with the shulker stack from quickshulkers, that has solved the titular issue
2. right clicking a stack of boxes has "no effect". It should have the "normal effect" of dividing the stack in 2, and putting the split in the cursor, like any other stackable. That is, right clicking a 64 boxes stack should end-up with 32 boxes in the original slot, and 32 boxes as the cursor.
3. right clicking a stack of boxes that have been RENAMED (e.g., anvil) erroneously splits the stack: 1 shulker remains in the current slot (RENAMED), while the 63 remaining shulkers are moved to the first empty inventory slot, and LOOSE THEIR NAME. 
4. If the inventory is full when the problem 3. is triggered, the 63 remaining boxes are DELETED, still resulting in item loss

Overall I believe that the correct fix is indeed to no Quick-open stacks, but in this case you should just defer the action to the prior method.

**Comment by MeeniMc** [comment]
BTW, stonecutters, crafting tables and ender chest cannot be 'divided' because stack opening is allowed for them. Not sure what is best in this case between "quick opening the stack" and "quick opening only 1-item stack" for these.

**Comment by kyrptonaught** [comment]
Ah that is a good point, perhaps I should only allow all items to be opened if they are a single stack, otherwise do the normal vanilla action that would have occurred.

**Comment by kyrptonaught** [comment]
This has been implemented in 1.3.0. I believe this solves all the issues here.
